### ISSUE TITLE
trackinglist.txt and Telegram

### ISSUE THREAD

**Issue by Zamana** [udithanuwanw/WhatsApp-Online-Activity-Tracker#2]
Hi!

Thanks for this project.

Two questions:

1) How the Telegram integration works? How do I link my Telegram with the tracking system?

2) It seems that the script is monitoring all my list of contacts, and not only the one that I put in trackinglist.txt. The WhatsApp web opened by ChromeDriver keeps pumping some chats and writing "test" in the message box...

Thanks.
Regards.

**Comment by Zamana** [comment]
Hi!

I figured out how to link with my Telegram. Solved.

Now I'm getting this error:

`Press Enter after scanning QR code...
Traceback (most recent call last):
  File "/Users/zamana/Projects/whats/whatsapp_tracker.py", line 295, in <module>
    el=driver.find_elements(By.XPATH,'//*[@role="textbox"]')[1]
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by udithanuwanw** [comment]
@Zamana Yes, it monitors the entire list of contacts and only tracks the numbers in trackinglist.txt. It sends some chats with the text 'test' to stay active on WhatsApp and remain online; otherwise, it hides the online status of WhatsApp users.

**Comment by Zamana** [comment]
Hi!

Now I'm getting this error:

<img width="788" alt="image" src="https://github.com/user-attachments/assets/09362fb6-28d9-4717-a6f4-4b570be37c55" />

"telegram" is installed through pip...

**Comment by Zamana** [comment]
And even removing "telegram" and installing "python-telegram-bot 21.9", the error is the same.

**Comment by Zamana** [comment]
Hi!

Now it's working fine!

Thank you very much.

**Comment by udithanuwanw** [comment]
@Zamana You're welcome :)
